### ISSUE TITLE
Note: It's not worth anyone's time to make a toxic community more accessible.

### ISSUE THREAD

**Issue by mhoye** [gvwilson/10-newcomers#12]
That is not a good use of anyone's time or effort.

**Comment by mhoye** [comment]
See: Julie Evans' "how to ask good questions" - https://jvns.ca/blog/good-questions/  - vs. Er.c Raym.nd's "Asking Sm.rt Questions".

**Comment by mhoye** [comment]
http://exple.tive.org/blarg/2018/11/09/the-evolution-of-open/

**Comment by gvwilson** [comment]
Incorporated into rules.tex as rule 9 in 97f6773.
