### ISSUE TITLE
Rule 9: Streamline and automate the setup of your development environment

### ISSUE THREAD

**Issue by mhoye** [gvwilson/10-newcomers#18]
This needs to be fleshed out a bit, but the gist of it is that getting set up to work on the project should be treated like a product - that is, made simple or automated as much as possible, with any unnecessary complexity sanded down or or removed.

**Comment by gvwilson** [comment]
Thanks - please assign to me when you've got 3-4 paragraphs. Will you be able to quote any data on e.g. uptick in contributions as Mozilla simplified Firefox dev setup?

**Comment by gvwilson** [comment]
ping
