### ISSUE TITLE
Develop forms of legitimate peripheral participation

### ISSUE THREAD

**Issue by dsholler** [gvwilson/10-newcomers#2]
Sets of simple, accessible tasks for newcomers can help to acclimate newcomers to the community, enhance feelings of self-efficacy, and demonstrate "legitimacy" to other community members. We might draw on the original Lave and Wenger definition to provide some examples (e.g., maintenance tasks, documentation).

**Comment by gvwilson** [comment]
Tracy Teal (from the Carpentries) is fond of the phrase "pathways to participation", and of having lots of 'em.

**Comment by igorsteinmacher** [comment]
This is a good thing. I see that labeling the tasks is the strategy that is adopted to make the 'first step' easier. I like the work "pathways" that Greg mentioned, to give the idea of a continuous effort to get someone onboard, going beyond the first task.

**Comment by igorsteinmacher** [comment]
Closed in #14
