### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dsholler** [gvwilson/10-newcomers#23]
Some comments:

1 - I agree with one of the other feedback-ers that we should be clear about the size of projects we're talking about here, or specify when certain rules apply or don't apply in particular sized projects

2 - I don't know too much about licensing, but I think we should fit that in somewhere. Specifically, something about making intellectual property rights/transfer clear in the guide to contributing (i.e., what happens when your code is merged to master)

3 - It seems I need to add something to my CoC section about why a CoC is necessary in the first place. To me, it's become kind of hard to imagine any argument against it being necessary... Although I can see why it might not make sense to spend time on one if the project is small, which relates to my point 1 above. Help me pull my head out of the sand on this one?

4 - I think I agree that we should change Rule 7 to "Treat opportunities for in-person interaction with care"

**Comment by gvwilson** [comment]
Most points closed by earlier commits; sizing comment closed by c7684ef
