### ISSUE TITLE
Inclusion in Ten Simple Rules collection at PLOS, DOI for this paper

### ISSUE THREAD

**Issue by pdurbin** [gvwilson/10-newcomers#27]
Hi! Is the plan for this paper to be included in the PLOS "Ten Simple Rules" collection at https://collections.plos.org/ten-simple-rules ?

Does this paper have a DOI like the other papers in that collection?

Thanks!

p.s. I heard about this paper at http://exple.tive.org/blarg/2019/08/07/ten-more-simple-rules/ and it looks great! Thanks for writing it! :tada:

**Comment by gvwilson** [comment]
Yes, it is being published in that collection, and we'll update this site with the DOI as soon as we have it (hopefully within the next couple of weeks).
