### ISSUE TITLE
Demonstrate that contributions of all kinds are equally valued

### ISSUE THREAD

**Issue by batpigandme** [gvwilson/10-newcomers#5]
Looking at open source projects as an ecosystem of spaces, I think we can expand the view of the _wheres_ for participation. 

Basically, I think there's something about the proliferation of participation spaces that makes this figure (in Ducheneaut 2005, who cites Moon and Sproull, 2000; Maas, 2004) seem a too static, and definitely intimidating:
![Current picture of OSS community organization.](https://user-images.githubusercontent.com/831732/50640463-f4b82100-0f32-11e9-9a8b-19a7fe53f3be.png)

Two areas in the lit to draw on (among others I'm sure):
* Prior social links that lead to "traditional" contribution

> Casalnuovo, Casey, Bogdan Vasilescu, Premkumar Devanbu, and Vladimir Filkov. 2015. “Developer Onboarding in GitHub: The Role of Prior Social Links and Language Experience.” Proceedings of the 2015 10th Joint Meeting on Foundations of Software Engineering - ESEC/FSE 2015, 817–28. doi:10.1145/2786805.2786854.

* Group attachment theory more broadly

> Ren, Yuqing, F. Maxwell Harper, Sara Drenner, Loren Terveen, Sara Kiesler, John Riedl, and Robert E. Kraut. 2012. “Building Member Attachment in Online Communities: Applying Theories of Group Identity and Interpersonal Bonds.” MIS Quarterly 36 (6): 55–83. doi:10.1002/smj.666.

> Ling, Kimberly, Gerard Beenen, Pamela Ludford, Xiaoqing Wang, Klarissa Chang, Xin Li, Dan Cosley, et al. n.d. “Using Social Psychology to Motivate Contributions to Online Communities.” Journal of Computer-Mediated Communication 10 (4): 0. doi:10.1111/j.1083-6101.2005.tb00273.x.

**Comment by gvwilson** [comment]
This figure, taken from (Ducheneaut 2005), portrays a common view of open source projects: programmers are at the center, and other activities such as reporting bugs or writing documentation are peripheral.  While widely held, especially by programmers, this perspective devalues some kinds of work and (implicitly) the people who do it.  To encourage legitimate peripheral participation, projects should value all kinds of contributions equally, and make that valuation clear.

For example, a project that one of the authors worked on required all new features to be blessed by the project's technical writer before being implemented: if the technical writer couldn't think of a way to explain it, the programmers were expected to find a way to simplify it.  This rule didn't just make the software more usable; it also signalled that technical writing was highly valued.  The testing team had similar authority: if they couldn't think of a way to test a new feature, they could veto it.  In practice, this meant that developers collaborated as equals early and often with people in other roles, which made the project more inviting for people who wished to contribute in those ways.

*This rule brought to you by Cassandra Wilson's version of "[Billie's Blues](https://www.youtube.com/watch?v=PB1HK-rlVig)".*

**Comment by gvwilson** [comment]
Closed by edfc427
