### ISSUE TITLE
Provide feedback quickly on first attempts at contribution

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/10-newcomers#8]
Make sure that newcomers' first attempts to contribute (through conversations or code) get a response quickly so that they believe someone is paying attention.

Q: does having a test suite newcomers can run easily count as providing feedback quickly? It isn't personal or human, but it does tell people whether they're on the right track.

**Comment by igorsteinmacher** [comment]
would we merge with #6 somehow? One rule about communication, maybe?

**Comment by igorsteinmacher** [comment]
Merging with #6
